### ISSUE TITLE
Event cloning with monthly interval fails

### ISSUE THREAD

**Issue by OmeGak** [indico/indico#1580]
``` yaml
# Ticket imported from Trac
```

Cloning an event with monthly intervals fails when the start date is set to the last day of a month with 31 days. This is caused by the way we iterate months: creating a new date object using the day of start_date. This happens both for _Clone the event with a fixed interval_ and _Clone the agenda on given days_.

For example:
An event whose repetition starts a 31st October will fail when trying to compose the 31st of November.

The patch should be done using dateutil.rrule in both cases.

For the first type of repetitions we should keep the day of the month unless it doesn't exist for a particular month. In that case we will create the event on the last day of the month. i.e. January 31, February 28, March 31, ...

For the second type of repetitions we should make sure that we don't skip months that don't have 5th weekday and creating the event on the 4th weekday as a fallback. i.e. 5th Sunday of November, 4th Sunday of December, ... 5th Sunday of March.

**Comment by ThiefMaster** [comment]
Most likely fixed in 2.0

**Comment by meluru** [comment]
The issue is not fixed for monthly repetition cloning that starts for example at 31st of October, the recurrence in November is ignored, instead of forced to compose last day of month.

According to dateuitl.rrule docs: 'recurrence instances falling on invalid dates and times are ignored rather than coerced'

**Comment by ThiefMaster** [comment]
@meluru can you add a `closes #1580` to your PR so this issue goes away when it's merged?

**Comment by meluru** [comment]
@ThiefMaster done
