### ISSUE TITLE
Registrants with "fake" (LDAP:xxxx id) avatars are a bit broken

### ISSUE THREAD

**Issue by ThiefMaster** [indico/indico#1850]
They have an avatar associated, so there's no "direct payment link" shown for them. However, they also cannot log in with that fake avatar.

We shouldn't associate fake avatars based on searching providers at all. Instead, we could maybe create a pending avatar or simply not associate an avatar with a registration unless the user is logged in...

**Comment by pferreir** [comment]
I guess this is now solved, with the modifications we've done to legacy user handling.

**Comment by ThiefMaster** [comment]
If we still search by email and associate a user even though the user wasn't logged in we probably still have the problem.

**Comment by pferreir** [comment]
Let's do that then.
