### ISSUE TITLE
Option "Full Edit" doesn't work while editing a contribution in a timetable

### ISSUE THREAD

**Issue by mic4ael** [indico/indico#1956]
Attempt to perform operations like 'Full edit' and 'Edit protection'  of a contribution in Timetable web page results in an error `Page not found`.

**Comment by pferreir** [comment]
I'm pretty sure this is fixed by 4f9900cad521c01ba9bdea4919523008c8ed1b16. Where do you see this happen?

**Comment by mic4ael** [comment]
Unfortunately, it doesn't fix the problem. The problem is that the url is formed incorrectly. I will take a more inquisitive look at this issue after I am done with things I am doing right now.

**Comment by mic4ael** [comment]
The problem occurs when adding a Contribution to Timetable of a Conference.

**Comment by mic4ael** [comment]
Now, I can't reproduce the problem. I think it was a problem specific to my instance of Indico (outdated application).
