### ISSUE TITLE
DB Error for partial anonymous survey

### ISSUE THREAD

**Issue by cfgmr** [indico/indico#3526]
Hi, 
we just finished a conference managed with indico and everything worked beautifully :)

Now we are having a small problem with the conference feedback survey: The survey is configured for **anonymous submission** and allows saving **partially filled out** questionnaires. If someones partially completes the survey and clicks **'Save answers' without being logged in**, an error message pops up stating that 'There was a database error while processing your request.'

The following error is reported in the logs:
```
2018-09-12 14:05:58,144  707b0368a85a419d  indico.flask - ERROR errors.py:107 -- (psycopg2.IntegrityError) new row for relation "submissions" violates check constraint "ck_submissions_submitted_and_anonymous_no_user"
```

We are running indico 2.1.3. If needed I can provide the full stack trace.

Cheers, 
Claas

**Comment by ThiefMaster** [comment]
We've already fixed that in 5a4a92a883648eeb5b4ecd7886194c0ddd9c5391 (2.1.4 which is unreleased) - you can safely apply the patch on your 2.1.3 version though.

**Comment by cfgmr** [comment]
Thanks! I 'fixed' the problem here by disabling disabling the option to save partially submission. We are happy to wait for 2.1.4, I just wanted to report in case you missed the bug.

**Comment by ThiefMaster** [comment]
Just FYI, 2.1.4 is out now!
